// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,se:6, verdadeiro:16, falso:18, e:34, ou:36, senao:40, enquanto:44, para:48, em:56, de:60, funcao:66, declare:72, constante:74}
export const parser = LRParser.deserialize({
  version: 14,
  states: "-UQYQPOOO!QQPOOOOQO'#Cc'#CcO!fQPO'#D`O%TQPO'#DSOOQO'#D`'#D`O!QQPO'#C`O%[QPO'#C{OOQO'#Dr'#DrOOQO'#D]'#D]OOQO'#DU'#DUQYQPOOOOQO'#Da'#DaO!aQPO'#C^O!aQPO'#CqO%cQPO'#CsO%cQPO'#C|O%hQPO'#DPQ$`QPOOO!QQPO'#CgOOQO,59Q,59QO!QQPO,59ZOOQO'#Ci'#CiOOQO'#Cj'#CjOOQO'#Ck'#CkOOQO'#Cl'#ClO!QQPO,59SO!QQPO,59SO!QQPO,59SO!QQPO,59SO!QQPO,59SO!QQPO,59SOOQO,59n,59nO%pQPO,58zOOQO,59g,59gO%wQPO,59gOOQO-E7S-E7SOYQPO,58xOYQPO,59]OOQO'#Cv'#CvO&OQPO'#CwOYQPO,59_O&ZQPO,59hO&`QPO,59kO%cQPO,59kO&hQPO'#DbO&rQPO,59RO&wQPO1G.uOOQO1G.n1G.nO)nQPO1G.nO+iQPO1G.nO+sQPO1G.nO+}QPO1G.nO,yQPO1G.nOOQO1G.f1G.fOOQO1G/R1G/RO.SQPO1G.dOOQO1G.w1G.wO!QQPO,59aO!QQPO,59cO!QQPO,59eOOQO1G.y1G.yO%cQPO'#DOO{QPO1G/SOOQO1G/V1G/VO!QQPO1G/VO/TQPO1G/VO!QQPO'#DVO/]QPO,59|OOQO1G.m1G.mOYQPO7+$OO/eQPO1G.{O/lQPO1G.}O0fQPO1G/PO1`QPO'#DsO1hQPO,59jOOQO7+$n7+$nO1mQPO7+$qOOQO7+$q7+$qO!QQPO7+$qO1tQPO,59qOOQO-E7T-E7TOOQO<<Gj<<GjO!QQPO7+$gO%cQPO'#DWO2OQPO,5:_OOQO1G/U1G/UOOQO<<H]<<H]O2WQPO<<H]O2_QPO<<HROOQO,59r,59rOOQO-E7U-E7UOOQOAN=wAN=w",
  stateData: "3X~O}OS!OOS~OR]OTTOUTOW[OX[Of^Oh_Oq`OtaO!QQO!RUO!dVO~OTTOUTOW[OX[O!QQO!RUO~O!RcO!beOa!SXb!SX!X!SX!Y!SX!Z!SX![!SX!]!SX!^!SX!_!SX!`!SX!a!SX!c!SX{!SX!W!SX!V!SXR!SXT!SXU!SXW!SXX!SXf!SXh!SXq!SXt!SX!Q!SX!d!SX~OanOboO!XfO!YgO!ZgO![hO!]hO!^hO!_hO!`iO!aiO~O!cpO~P$`O!erO~PYO!QwO~Ou|O!QwO~O!W!WO~P$`O!e!XO~PYOl!]On!^O!c![O~O!R!`O~O!b!cO!c!bO~O!V!eO!W!UX~P$`O!W!gO~O!cci{ci!Wci!VciRciTciUciWciXcifcihciqcitci!Qci!Rci!dci~P$`O!XfOa[ib[i![[i!][i!^[i!_[i!`[i!a[i!c[i{[i!W[i!V[iR[iT[iU[iW[iX[if[ih[iq[it[i!Q[i!R[i!d[i~O!YgO!ZgO~P'}O!XfO!YgO!ZgO![hO!]hO!^hO!_hOa[ib[i!c[i{[i!W[i!V[iR[iT[iU[iW[iX[if[ih[iq[it[i!Q[i!R[i!d[i~O!`[i!a[i~P)xO!Y[i!Z[i~P'}O!`iO!aiO~P)xOanO!XfO!YgO!ZgO![hO!]hO!^hO!_hO!`iO!aiO~Ob[i!c[i{[i!W[i!V[iR[iT[iU[iW[iX[if[ih[iq[it[i!Q[i!R[i!d[i~P,XOd!hORQiTQiUQiWQiXQifQihQiqQitQi{Qi!QQi!RQi!dQi!eQi~O!b!qO!c!pO~O!V!eO!W!Ua~O!c!uO~P$`ORkiTkiUkiWkiXkifkihkiqkitki!Qki!Rki!dki~P$`ORmiTmiUmiWmiXmifmihmiqmitmi!Qmi!Rmi!dmi~P$`O!V!vO!W!gX~O!W!xO~O!c!yO~P$`O!Vya!Wya~P$`O!V!vO!W!ga~O!c#OO~P$`ORiyTiyUiyWiyXiyfiyhiyqiytiy!Qiy!Riy!diy~P$`O",
  goto: ")k!hPP!iP!sPP#fPP$R$n$R$q%U%h%yPP$RP!iP!iP&Z&^&ZP&ZP&p&}P'X&}PP!iP'['f'lPPPP'rPP(U$R)ePPPPPPPPPPPPPPP!i)haXOVZsuvy!h!STOPUVZcejklmnosuvy![!]!^!c!e!h!q!uQu]Rv^!TROPUVZcejklmnosuvy![!]!^!c!e!h!q!u!TTOPUVZcejklmnosuvy![!]!^!c!e!h!q!uRdRsjSbq}!P!R!S!T!U!V!i!j!k!o!r!z!{qmSbq}!P!R!S!U!V!i!j!k!o!r!z!{okSbq}!P!S!U!V!i!j!k!o!r!z!{mlSbq}!P!U!V!i!j!k!o!r!z!{Ry_Qx_Qz`Q{aQ!d|Q!l!`R!|!v`XOVZsuvy!hR!n!aaWOVZsuvy!hR!azQZOQsVTtZsQ!f}R!s!fQ!w!lR!}!wWYOVZsQ!YuQ!ZvQ!_yR!t!h`SOVZsuvy!hQbPQqUQ}cQ!PeQ!QjQ!RkQ!SlQ!TmQ!UnQ!VoQ!i![Q!j!]Q!k!^Q!o!cQ!r!eQ!z!qR!{!uR!OcR!m!`",
  nodeNames: "⚠ Script IfStatement se ParenthesizedExpression Number String VariableName verdadeiro falso CallExpression ArgList BinaryExpression ArithOp ArithOp CompareOp CompareOp e ou AssignmentExpression senao WhileStatement enquanto ForStatement para ForSpec VariableDefinition ForInSpec em ForOfSpec de Block FunctionDeclaration funcao ParamList VariableDeclaration declare constante ExpressionStatement SingleExpression",
  maxTerm: 69,
  nodeProps: [
    ["group", -7,2,21,23,31,32,35,38,"Statement",-9,4,5,6,7,8,9,10,12,19,"Expression"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "(e~RoXY#SYZ#tZ[#S]^#tqr#yrs$Uxy$yyz%Oz{%T{|%Y|}%_}!O%d!Q![%i!]!^&z!^!_'P!_!`'^!`!a'k!c!}'x#R#S'x#T#o'x#o#p(Z#q#r(`$f$g#S#BY#BZ#S$IS$I_#S$I|$I}#t$I}$JO#t$JT$JU#S$KV$KW#S&FU&FV#S?HT?HU#S~#XX}~XY#SZ[#S$f$g#S#BY#BZ#S$IS$I_#S$JT$JU#S$KV$KW#S&FU&FV#S?HT?HU#S~#yO!O~~#|P!_!`$P~$UO!a~~$XVOr$Urs$ns#O$U#O#P$U#P;'S$U;'S;=`$s<%lO$U~$sOU~~$vP;=`<%l$U~%OO!R~~%TO!W~~%YO!X~~%_O!Y~~%dO!V~~%iO!Z~~%nST~!O!P%z!Q![%i!g!h&`#X#Y&`~%}P!Q![&Q~&VRT~!Q![&Q!g!h&`#X#Y&`~&cR{|&l}!O&l!Q![&r~&oP!Q![&r~&wPT~!Q![&r~'PO!c~~'UP![~!_!`'X~'^O!]~~'cP!b~!_!`'f~'kO!`~~'pP!^~!_!`'s~'xO!_~~'}S!Q~!Q!['x!c!}'x#R#S'x#T#o'x~(`O!d~~(eO!e~",
  tokenizers: [0],
  topRules: {"Script":[0,1],"SingleExpression":[1,39]},
  dialects: {cobral: 0},
  specialized: [{term: 48, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 0
})
