[package]
name = "lexer"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
name = "lexer"
path = "src/lexer.rs"

[dependencies]
enums.workspace = true
logger.workspace = true
libs.workspace = true
tauri.workspace = true