name: Webhook
on:
  release:
    types: [published]

jobs:      
  webhook-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Read CHANGELOG
        id: read
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: CHANGELOG.md

      - name: Send a request to webhook
        run: |
          RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
          "content": "${{ steps.read.outputs.content }}"
          }' ${{ secrets.WEBHOOK_URL }})
          echo "Webhook server response: $RESPONSE"